spring.application.name: entity-ms
spring.profiles.active: local

info:
  app.name: ${spring.application.name}
  app.version: LOCAL

server:
  port:  4050
  error:
    include-message: always

h2.console:
  port: 4051

traceability:
  headers:
    applicationId: x-trace-appl
    duration: x-trace-duration
    requestId: x-trace-request-id
    transactionId: x-trace-transaction-id
    applicationName: ${spring.application.name}

management:
  endpoints:
    web:
      base-path: /mgmt
      exposure:
        include: "*"
    enabled-by-default: false
  endpoint:
    beans:
      enabled: true
    configprops:
      enabled: true
    env:
      enabled: true
    health:
      enabled: true
      show-details: always
    info:
      enabled: true
    metrics:
      enabled: true
    shutdown:
      enabled: true

entity-service:
  entities:
    - type: item
      properties:
        - type: tags
          projection: DETAILS
    - type: thing
      properties:
        - type: tags
          projection: DETAILS
        - type: groups
          projection: DEEP
